### ISSUE TITLE
Question about the "Quick Start" code

### ISSUE THREAD

**Issue by eulovi** [tataratat/gustaf#124]
Dear Gustaf-Team,

After installing `gustaf` and its dependencies I ran the "Quick Start" code displayed in the Readme. It works until line 126 for:
```
gus.show(
    ["NURBS and translated tet together", nurbs, tet],
    ["Extruded NURBS", extruded],
    ["Revolved NURBS", revolved],
    ["NURBS parametric view", parametric_view],
)
```
Then I get the following error (sorry for the long output):

```
Traceback (most recent call last):
  File "testing-gus.py", line 126, in <module>
    gus.show(
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/show.py", line 32, in __call__
    return show(*args, **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/show.py", line 52, in show
    return show_vedo(*gus_obj, **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/show.py", line 157, in show_vedo
    tmp_showable = item.showable(backend="vedo", **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/base.py", line 217, in showable
    return show(self, return_showable=True, **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/base.py", line 77, in show
    things_to_show = visualize.make_showable(spline)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/visualize.py", line 92, in make_showable
    return eval(f"_{spline.show_options._backend}_showable(spline)")
  File "<string>", line 1, in <module>
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/visualize.py", line 109, in _vedo_showable
    gus_primitives = eval(f"_vedo_showable_para_dim_{spline.para_dim}(spline)")
  File "<string>", line 1, in <module>
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/visualize.py", line 340, in _vedo_showable_para_dim_3
    return _vedo_showable_para_dim_2(spline)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/visualize.py", line 323, in _vedo_showable_para_dim_2
    sp = spline.extract.faces(res)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/extract.py", line 506, in faces
    return faces(self._spline, *args, **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/spline/extract.py", line 243, in faces
    f.merge_vertices()
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/vertices.py", line 485, in merge_vertices
    unique_vs = self.unique_vertices()
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/helpers/data.py", line 390, in compute_or_return_saved
    computed = func(*args, **kwargs)
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/vertices.py", line 312, in unique_vertices
    values, ids, inverse, intersection = utils.arr.close_rows(
  File "/home/a11beulo/.local/lib/python3.8/site-packages/gustaf/utils/arr.py", line 155, in close_rows
    neighbors = kdt.query_ball_point(
  File "ckdtree.pyx", line 910, in scipy.spatial.ckdtree.cKDTree.query_ball_point
  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

I wonder if I missed something during the installation, which I did with `pip install gustaf[all]`. If you could give me some insight of what I did wrong, please let me know.

Thanks in advance!

Kind regards, 
Gabriela Loera

**Comment by j042** [comment]
Hi Gabriela, thanks for reporting this! I couldn't reproduce this error, but it seems that the error comes from scipy's `cKDTree`. You could try updating scipy:
```
pip install --upgrade scipy
```
Let me know if this helps
