### ISSUE TITLE
can not copy spline

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/gustaf#89]
What happens: Can not copy working spline with spline build-in copy function. Throws the following error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rwthfs/rz/cluster/home/cf931719/git/gustaf/gustaf/spline/base.py", line 222, in copy
    new = type(self)()
  File "/rwthfs/rz/cluster/home/cf931719/git/gustaf/gustaf/spline/base.py", line 424, in __init__
    splinepy.BSpline.__init__(
  File "/home/cf931719/miniconda3/envs/installed-releso/lib/python3.9/site-packages/splinepy-0.0.3-py3.9-linux-x86_64.egg/splinepy/bspline.py", line 186, in __init__
    super().__init__(
  File "/home/cf931719/miniconda3/envs/installed-releso/lib/python3.9/site-packages/splinepy-0.0.3-py3.9-linux-x86_64.egg/splinepy/bspline.py", line 28, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cf931719/miniconda3/envs/installed-releso/lib/python3.9/site-packages/splinepy-0.0.3-py3.9-linux-x86_64.egg/splinepy/spline.py", line 485, in __init__
    super().__init__(**kwargs)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

What should happen: Spline can be copied without error.

Steps to reproduce, see image:
![image](https://user-images.githubusercontent.com/3420870/212281021-eb8582e3-b083-4bc3-a02e-9de0719bcdfb.png)

```
import gustaf as gus
temp_spline = gus.BSpline(
  [2, 2],
  [[0, 0, 0, 0.33, 0.66, 1, 1, 1], [0, 0, 0, 1, 1, 1]],
  [
      [0, 0],
      [0.25, 0],
      [0.5, 0.05],
      [0.75, 0.1],
      [1, 0.1],
      [0, 0.2],
      [0.25, 0.2],
      [0.5, 0.2],
      [0.75, 0.2],
      [1, 0.2],
      [0, 0.4],
      [0.25, 0.4],
      [0.5, 0.35],
      [0.75, 0.3],
      [1, 0.3],
  ],
)
temp_spline.copy()
```

**Comment by clemens-fricke** [comment]
The relevant function in gustaf also has the following comment:
```
"""tmp copy from splinepy until #89 merges"""
```

**Comment by clemens-fricke** [comment]
Is fixed with a fresh installation of splinepy. Welp sorry.
